# Generated by Django 5.0.2 on 2024-03-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_curso_remove_cursos_nombre_cursos_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterModelTable(
            name='cursos',
            table='aplicacion_curso',
        ),
    ]
