# Generated by Django 5.0.2 on 2024-03-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_delete_curso_alter_cursos_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={},
        ),
        migrations.AlterModelTable(
            name='cursos',
            table=None,
        ),
    ]
